import { createContext, useContext, useState } from "react";

export type Lang = "en" | "hi" | "te" | "ta";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.careers": "Careers",
    "nav.roadmap": "Roadmap",
    "nav.resume": "Resume",
    "nav.courses": "Courses",
    "nav.centers": "Centers",
    "nav.sattva": "Sattva",
    "hero.badge": "Empowering India's Youth",
    "hero.title1": "Navigate Your Future with",
    "hero.title2": "AI Precision",
    "hero.subtitle": "Discover your perfect career, analyze your skills, and get a step-by-step roadmap to success. Your personal AI career counselor, available 24/7.",
    "hero.placeholder": "Search your dream career...",
    "hero.cta": "Get Started",
    "hero.stat1": "Careers Mapped",
    "hero.stat2": "Match Accuracy",
    "hero.stat3": "AI Guidance",
    "fields.title": "Explore Fields",
    "fields.subtitle": "Find your passion across emerging industries",
    "features.title": "A Complete Career Ecosystem",
    "features.subtitle": "Everything you need to chart your course from learning to earning.",
    "cta.title": "Ready to find your calling?",
    "cta.subtitle": "Join thousands of students mapping their future with AI Career Navigator.",
    "cta.button": "Start Free Assessment",
    "footer.credit": "Designed by Team Sattva | Ignite 2K26",
    "login.button": "Sign in",
    "login.title": "Sign in to AI Career Navigator",
    "login.google": "Continue with Google",
    "login.guest": "Continue as Guest",
    "grade.title": "Select Your Current Standard",
    "grade.subtitle": "This helps us personalize career guidance for your level.",
    "grade.confirm": "Confirm & Continue",
    "grade.6": "Class 6",
    "grade.7": "Class 7",
    "grade.8": "Class 8",
    "grade.9": "Class 9",
    "grade.10": "Class 10",
    "grade.intermediate": "Intermediate (11–12)",
    "grade.above": "Graduation & Above",
    "notification.welcome": "Welcome back",
    "notification.lastVisited": "You were last on",
    "notification.resume": "Continue from where you left off",
    "chat.realGuider": "Talk to a Real Counselor",
    "chat.aiMentor": "AI Mentor (Sattva)",
    "intermediate.title": "Intermediate Foundation Guide",
    "intermediate.jee": "JEE Preparation",
    "intermediate.eamcet": "EAMCET Preparation",
    "intermediate.mpc": "MPC Stream Cutoffs",
  },
  hi: {
    "nav.home": "होम",
    "nav.careers": "करियर",
    "nav.roadmap": "रोडमैप",
    "nav.resume": "रेज़ुमे",
    "nav.courses": "कोर्स",
    "nav.centers": "केंद्र",
    "nav.sattva": "सत्त्व",
    "hero.badge": "भारत के युवाओं को सशक्त बनाना",
    "hero.title1": "अपने भविष्य को नेविगेट करें",
    "hero.title2": "AI की सटीकता से",
    "hero.subtitle": "अपना परफेक्ट करियर खोजें, अपनी स्किल्स का विश्लेषण करें और सफलता का स्टेप-बाय-स्टेप रोडमैप पाएं।",
    "hero.placeholder": "अपना सपनों का करियर खोजें...",
    "hero.cta": "शुरू करें",
    "hero.stat1": "करियर मैप्ड",
    "hero.stat2": "मैच सटीकता",
    "hero.stat3": "AI मार्गदर्शन",
    "fields.title": "क्षेत्र खोजें",
    "fields.subtitle": "उभरते उद्योगों में अपना जुनून खोजें",
    "features.title": "एक पूर्ण करियर इकोसिस्टम",
    "features.subtitle": "सीखने से कमाने तक का सब कुछ।",
    "cta.title": "अपनी पुकार खोजने के लिए तैयार हैं?",
    "cta.subtitle": "हजारों छात्रों के साथ जुड़ें जो AI Career Navigator से अपना भविष्य बना रहे हैं।",
    "cta.button": "मुफ्त मूल्यांकन शुरू करें",
    "footer.credit": "टीम सत्त्व द्वारा | Ignite 2K26",
    "login.button": "साइन इन",
    "login.title": "AI Career Navigator में साइन इन करें",
    "login.google": "Google से जारी रखें",
    "login.guest": "अतिथि के रूप में जारी रखें",
    "grade.title": "अपनी वर्तमान कक्षा चुनें",
    "grade.subtitle": "यह आपके स्तर के अनुसार करियर मार्गदर्शन को व्यक्तिगत बनाने में मदद करता है।",
    "grade.confirm": "पुष्टि करें और जारी रखें",
    "grade.6": "कक्षा 6",
    "grade.7": "कक्षा 7",
    "grade.8": "कक्षा 8",
    "grade.9": "कक्षा 9",
    "grade.10": "कक्षा 10",
    "grade.intermediate": "इंटरमीडिएट (11–12)",
    "grade.above": "स्नातक एवं ऊपर",
    "notification.welcome": "वापस स्वागत है",
    "notification.lastVisited": "आप अंतिम बार थे",
    "notification.resume": "जहाँ छोड़ा था वहाँ से जारी रखें",
    "chat.realGuider": "वास्तविक परामर्शदाता से बात करें",
    "chat.aiMentor": "AI मेंटर (सत्त्व)",
    "intermediate.title": "इंटरमीडिएट फाउंडेशन गाइड",
    "intermediate.jee": "JEE तैयारी",
    "intermediate.eamcet": "EAMCET तैयारी",
    "intermediate.mpc": "MPC स्ट्रीम कटऑफ",
  },
  te: {
    "nav.home": "హోమ్",
    "nav.careers": "కెరీర్లు",
    "nav.roadmap": "రోడ్‌మ్యాప్",
    "nav.resume": "రెజ్యుమె",
    "nav.courses": "కోర్సులు",
    "nav.centers": "కేంద్రాలు",
    "nav.sattva": "సత్త్వ",
    "hero.badge": "భారత యువతను సాధికారం చేయడం",
    "hero.title1": "మీ భవిష్యత్తును నావిగేట్ చేయండి",
    "hero.title2": "AI ఖచ్చితత్వంతో",
    "hero.subtitle": "మీ పర్ఫెక్ట్ కెరీర్ కనుగొనండి, నైపుణ్యాలను విశ్లేషించండి మరియు విజయానికి దశలవారీ రోడ్‌మ్యాప్ పొందండి.",
    "hero.placeholder": "మీ కలల కెరీర్ వెతకండి...",
    "hero.cta": "ప్రారంభించండి",
    "hero.stat1": "మ్యాప్ చేసిన కెరీర్లు",
    "hero.stat2": "మ్యాచ్ ఖచ్చితత్వం",
    "hero.stat3": "AI మార్గదర్శనం",
    "fields.title": "రంగాలు అన్వేషించండి",
    "fields.subtitle": "అభివృద్ధి చెందుతున్న పరిశ్రమలలో మీ అభిరుచిని కనుగొనండి",
    "features.title": "పూర్తి కెరీర్ ఎకోసిస్టమ్",
    "features.subtitle": "నేర్చుకోవడం నుండి సంపాదించడం వరకు అన్నీ.",
    "cta.title": "మీ పిలుపు కనుగొనడానికి సిద్ధంగా ఉన్నారా?",
    "cta.subtitle": "AI Career Navigator తో వారి భవిష్యత్తును మ్యాప్ చేస్తున్న వేలాది విద్యార్థులతో చేరండి.",
    "cta.button": "ఉచిత అంచనా ప్రారంభించండి",
    "footer.credit": "సత్త్వ బృందం రూపొందించింది | Ignite 2K26",
    "login.button": "సైన్ ఇన్",
    "login.title": "AI Career Navigator లో సైన్ ఇన్ చేయండి",
    "login.google": "Google తో కొనసాగండి",
    "login.guest": "అతిథిగా కొనసాగండి",
    "grade.title": "మీ ప్రస్తుత తరగతి ఎంచుకోండి",
    "grade.subtitle": "ఇది మీ స్థాయికి అనుగుణంగా కెరీర్ మార్గదర్శనాన్ని వ్యక్తిగతీకరించడంలో సహాయపడుతుంది.",
    "grade.confirm": "నిర్ధారించి కొనసాగండి",
    "grade.6": "6వ తరగతి",
    "grade.7": "7వ తరగతి",
    "grade.8": "8వ తరగతి",
    "grade.9": "9వ తరగతి",
    "grade.10": "10వ తరగతి",
    "grade.intermediate": "ఇంటర్మీడియట్ (11–12)",
    "grade.above": "గ్రాడ్యుయేషన్ & పైన",
    "notification.welcome": "తిరిగి స్వాగతం",
    "notification.lastVisited": "మీరు చివరిగా ఉన్నారు",
    "notification.resume": "మీరు వదిలిపెట్టిన చోట నుండి కొనసాగండి",
    "chat.realGuider": "నిజమైన సలహాదారుతో మాట్లాడండి",
    "chat.aiMentor": "AI మెంటర్ (సత్త్వ)",
    "intermediate.title": "ఇంటర్మీడియట్ ఫౌండేషన్ గైడ్",
    "intermediate.jee": "JEE తయారీ",
    "intermediate.eamcet": "EAMCET తయారీ",
    "intermediate.mpc": "MPC స్ట్రీమ్ కటాఫ్‌లు",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.careers": "தொழில்கள்",
    "nav.roadmap": "பாதை வரைபடம்",
    "nav.resume": "விண்ணப்பம்",
    "nav.courses": "படிப்புகள்",
    "nav.centers": "மையங்கள்",
    "nav.sattva": "சத்வா",
    "hero.badge": "இந்தியாவின் இளைஞர்களை மேம்படுத்துகிறோம்",
    "hero.title1": "உங்கள் எதிர்காலத்தை வழிசெலுத்துங்கள்",
    "hero.title2": "AI துல்லியத்துடன்",
    "hero.subtitle": "உங்கள் சரியான தொழிலை கண்டறியுங்கள், திறன்களை பகுப்பாய்வு செய்யுங்கள், வெற்றிக்கான படிப்படியான வரைபடம் பெறுங்கள்.",
    "hero.placeholder": "உங்கள் கனவு தொழிலை தேடுங்கள்...",
    "hero.cta": "தொடங்குங்கள்",
    "hero.stat1": "வரைபடமிடப்பட்ட தொழில்கள்",
    "hero.stat2": "பொருத்த துல்லியம்",
    "hero.stat3": "AI வழிகாட்டுதல்",
    "fields.title": "துறைகளை ஆராயுங்கள்",
    "fields.subtitle": "வளர்ந்துவரும் துறைகளில் உங்கள் ஆர்வத்தை கண்டறியுங்கள்",
    "features.title": "முழுமையான தொழில் சூழல்",
    "features.subtitle": "கற்றலிலிருந்து சம்பாதிப்பது வரை அனைத்தும்.",
    "cta.title": "உங்கள் அழைப்பை கண்டறிய தயாரா?",
    "cta.subtitle": "AI Career Navigator மூலம் தங்கள் எதிர்காலத்தை வரைபடமிடும் ஆயிரக்கணக்கான மாணவர்களுடன் சேருங்கள்.",
    "cta.button": "இலவச மதிப்பீடு தொடங்குக",
    "footer.credit": "சத்வா குழுவால் வடிவமைக்கப்பட்டது | Ignite 2K26",
    "login.button": "உள்நுழைக",
    "login.title": "AI Career Navigator இல் உள்நுழைக",
    "login.google": "Google மூலம் தொடரவும்",
    "login.guest": "விருந்தினராக தொடரவும்",
    "grade.title": "உங்கள் தற்போதைய வகுப்பை தேர்ந்தெடுக்கவும்",
    "grade.subtitle": "இது உங்கள் நிலைக்கு ஏற்ப தொழில் வழிகாட்டுதலை தனிப்பயனாக்க உதவுகிறது.",
    "grade.confirm": "உறுதிப்படுத்தி தொடரவும்",
    "grade.6": "6ஆம் வகுப்பு",
    "grade.7": "7ஆம் வகுப்பு",
    "grade.8": "8ஆம் வகுப்பு",
    "grade.9": "9ஆம் வகுப்பு",
    "grade.10": "10ஆம் வகுப்பு",
    "grade.intermediate": "இடைநிலை (11–12)",
    "grade.above": "பட்டப்படிப்பு & அதற்கு மேல்",
    "notification.welcome": "மீண்டும் வரவேற்கிறோம்",
    "notification.lastVisited": "நீங்கள் கடைசியாக இருந்தீர்கள்",
    "notification.resume": "நீங்கள் விட்டுச் சென்ற இடத்திலிருந்து தொடரவும்",
    "chat.realGuider": "உண்மையான ஆலோசகரிடம் பேசுங்கள்",
    "chat.aiMentor": "AI வழிகாட்டி (சத்வா)",
    "intermediate.title": "இடைநிலை அடிப்படை வழிகாட்டி",
    "intermediate.jee": "JEE தயாரிப்பு",
    "intermediate.eamcet": "EAMCET தயாரிப்பு",
    "intermediate.mpc": "MPC ஸ்ட்ரீம் கட்-ஆஃப்",
  }
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("lang") as Lang) || "en";
    }
    return "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string) => translations[lang][key] || translations["en"][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
